directories:
  output: release
  buildResources: assets
appId: com.iacula.app
productName: Iacula
files:
  - filter:
      - dist/**/*
      - assets/**/*
extraResources:
  - from: assets
    to: assets
win:
  target: nsis
  compression: maximum
  icon: assets/images/icon.ico
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  deleteAppDataOnUninstall: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
  runAfterFinish: true
  artifactName: ${productName}-Setup-${version}.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  differentialPackage: true
linux:
  target: deb
  category: Utility
  maintainer: Gabriel Tavares <gabrieltxtavares@gmail.com>
  compression: null
  icon: assets/images/icon.png
mac:
  target: dmg
  category: public.app-category.utilities
  compression: maximum
  icon: assets/images/icon.icns
  identity: null
  hardenedRuntime: false
  gatekeeperAssess: false
afterSign: null
publish:
  provider: github
  releaseType: release
compression: maximum
asar: true
asarUnpack:
  - assets/**/*
electronVersion: 28.3.3
